### PR TITLE
Dockerfile & few updates

### PR DESCRIPTION
**Pull request by GoliathLabs**
Hello,
@T0biii and I are currently working on the meshviewer. We have updated a few dependencies, added Github actions to automatically create a Docker image and push it to the ghcr container registry, and can confirm that everything works on our local test setups.

Please squash the commits when this PR is being merged :)

### CODE REVIEW

**Review by awlx — APPROVED** [review]
I have no idea what's going on but awesome that you take on the project and I look forward to your stuff :). 

If you feel comfortable merge it. Please know it's going to be deployed to prod on merge.

**Review by T0biii — APPROVED** [review]
LGTM

**Comment by GoliathLabs** [comment]
Perfect. We both want to work on it in the next few weeks/months. Sadly we both don't have the permission to merge the PR just yet

**Comment by GoliathLabs** [comment]
You might want to add the website & salt-stack teams as maintainers to this repo @awlx

**Comment by awlx** [comment]
Nope we might want a new group

**Comment by GoliathLabs** [comment]
You did forget to squash the PR 😄

**Pull request merged**
